version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - Tiryoh
  assignees:
  - Tiryoh
  labels:
  - dependencies
  - ruby
  ignore:
  - dependency-name: faraday
    versions:
    - 1.4.0
  - dependency-name: ethon
    versions:
    - 0.13.0
  - dependency-name: nokogiri
    versions:
    - 1.11.2
    - 1.11.3
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: nokogumbo
    versions:
    - 2.0.5
  - dependency-name: ruby2_keywords
    versions:
    - 0.0.4
  - dependency-name: faraday-net_http
    versions:
    - 1.0.1
  - dependency-name: html-proofer
    versions:
    - 3.18.6
    - 3.18.8
  - dependency-name: minitest
    versions:
    - 5.14.3
    - 5.14.4
  - dependency-name: activesupport
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.3
  - dependency-name: jekyll-data
    versions:
    - 1.1.1
  - dependency-name: i18n
    versions:
    - 1.8.7
    - 1.8.8
  - dependency-name: concurrent-ruby
    versions:
    - 1.1.8
  - dependency-name: tzinfo
    versions:
    - 2.0.4
  commit-message:
    prefix: chore
