version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - Tiryoh
  assignees:
  - Tiryoh
  labels:
  - "Type: Dependencies"
  - "Lang: Ruby"
  commit-message:
    prefix: chore
